//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbsthalk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favourite
    {
        public int ID { get; set; }
        public string TypeID { get; set; }
        public int RelatedID { get; set; }
        public int AccountID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Answer Answer { get; set; }
        public virtual Blog Blog { get; set; }
        public virtual Question Question { get; set; }
        public virtual Tutorial Tutorial { get; set; }
    }
}
