//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbsthalk.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HbsthalkEntities : DbContext
    {
        public HbsthalkEntities()
            : base("name=HbsthalkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<Complete> Completes { get; set; }
        public virtual DbSet<Contest> Contests { get; set; }
        public virtual DbSet<DiscussionRoom> DiscussionRooms { get; set; }
        public virtual DbSet<Favourite> Favourites { get; set; }
        public virtual DbSet<MCQ> MCQs { get; set; }
        public virtual DbSet<Mention> Mentions { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<PreferenceList> PreferenceLists { get; set; }
        public virtual DbSet<Proficiency> Proficiencies { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<TrueFalse> TrueFalses { get; set; }
        public virtual DbSet<Tutorial> Tutorials { get; set; }
        public virtual DbSet<TutorialMaterial> TutorialMaterials { get; set; }
        public virtual DbSet<ContestAnswer> ContestAnswers { get; set; }
        public virtual DbSet<ContestRelation> ContestRelations { get; set; }
        public virtual DbSet<FollowZone> FollowZones { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Lesson> Lessons { get; set; }
        public virtual DbSet<TagRelation> TagRelations { get; set; }
    }
}
