//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbsthalk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reply
    {
        public int ID { get; set; }
        public int AnswerID { get; set; }
        public string Text { get; set; }
        public string FilePath { get; set; }
    
        public virtual Answer Answer { get; set; }
    }
}
