//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbsthalk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public int ID { get; set; }
        public string Text { get; set; }
        public string RelationType { get; set; }
        public int RelatedID { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Application Application { get; set; }
        public virtual Blog Blog { get; set; }
        public virtual DiscussionRoom DiscussionRoom { get; set; }
        public virtual Question Question { get; set; }
    }
}
