//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbsthalk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorialMaterial
    {
        public int ID { get; set; }
        public string FilePath { get; set; }
        public int TutorialID { get; set; }
        public string FileType { get; set; }
    
        public virtual Tutorial Tutorial { get; set; }
    }
}
